### ISSUE TITLE
Leftover cookie when server started freshly causes error

### ISSUE THREAD

**Issue by TheBizzle** [TheBizzle/rusted-wheel#11]
If you have a cookie already registered in your browser, and you try to connect to the server after restarting it, it results in this error:

> thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323

If you clear your cookies, it goes away.

**Comment by fluffywaffles** [comment]
Closed by mad trickery and science AKA 19ce575
